name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: make install

      - name: Run Linter
        run: make lint

      # Если добавите таргет `test: uv run pytest` в Makefile, 
      # здесь можно будет просто вызывать `make test`
      - name: Run Tests
        env:
          SECRET_KEY: "ci-secret-key-for-tests"
        run: uv run pytest
